//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prestamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamos()
        {
            this.Activos = new HashSet<Activos>();
            this.ComplexProperty = new equipo();
        }
    
        public int Id { get; set; }
        public string NumeroBoleta { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaRetiro { get; set; }
        public int PeriodoUso { get; set; }
        public string SoftwareReq { get; set; }
        public string ObservacionesSolicitante { get; set; }
        public string ObservacionesAprobado { get; set; }
        public string ObservacionesRecibido { get; set; }
    
        public equipo ComplexProperty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activos> Activos { get; set; }
    }
}
